name: CI/CD Secure Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install pytest safety bandit

      - name: Run tests
        run: python -m pytest

      - name: Scan dependencies (SCA)
        run: safety check

      - name: Static code analysis (SAST)
        run: bandit -r .

  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
